# Changes here will be overwritten by Copier
_commit: cdb1adc
_src_path: https://github.com/cagov/caldata-infrastructure-template
dbt_profile_name: caldata_engaged_california
email_address: odi-caldata-dse@innovation.ca.gov
friendly_project_name: Caldata Engaged California
license: MIT
project_name: caldata-engaged-california
team_name: Caldata Data Operations and Engineering
