select
POLY_INCIDENTNAME AS Name
, FIRE_DISCOVERY_DATETIME
, CONTAINMENT_DATETIME
, CONTROL_DATETIME
, FIRE_OUT_DATETIME
, POLY_GISACRES as Acres
, PERIMETER_GEOGRAPHY
FROM  {{ ref('stg_ca_fire_perimeters') }}
where FIRE_DISCOVERY_DATETIME >= '2024-11-01' and POLY_GISACRES > 40
