WITH source_seed AS (
    SELECT *
    FROM {{ source('LA_FIRES_GEO', 'CA_FIRE_PERIMETERS') }}
)

SELECT
    -- Polygon Attributes
    poly_sourceoid,
    poly_incidentname,
    poly_featurecategory,
    poly_mapmethod,
    poly_gisacres,
    poly_featureaccess,
    poly_featurestatus,
    poly_isvisible,
    -- Attempt basic parse, relies on Snowflake's default formats
    poly_createdate AS perimeter_createdate,
    poly_datecurrent AS perimeter_date_current,
    poly_polygondatetime AS perimeter_polygon_datetime_ntz, // Already TIMESTAMP_NTZ, keep as is
    poly_irwinid AS perimeter_irwinid,
    poly_forid AS perimeter_forid,
    poly_acres_autocalc,
    poly_sourceglobalid AS perimeter_sourceglobalid, // Alias to distinguish if joining
    poly_source AS perimeter_source,

    -- Incident Attributes (selecting all, casting dates)
    attr_sourceoid,
    attr_abcdmisc,
    attr_adspermissionstate,
    attr_calculatedacres,
    attr_containmentdatetime AS containment_datetime,
    attr_controldatetime AS control_datetime,
    attr_createdbysystem,
    attr_incidentsize,
    attr_discoveryacres,
    attr_dispatchcenterid,
    attr_estimatedcosttodate,
    attr_finalacres,
    attr_ffreportapprovedbytitle,
    attr_ffreportapprovedbyunit,
    attr_ffreportapproveddate AS ff_report_approved_date,
    attr_firebehaviorgeneral,
    attr_firebehaviorgeneral1,
    attr_firebehaviorgeneral2,
    attr_firebehaviorgeneral3,
    attr_firecause,
    attr_firecausegeneral,
    attr_firecausespecific,
    attr_firecode,
    attr_firedepartmentid,
    attr_firediscoverydatetime AS fire_discovery_datetime,
    attr_firemgmtcomplexity,
    attr_fireoutdatetime AS fire_out_datetime,
    attr_firestrategyconfinepercent,
    attr_firestrategyfullsuppprcnt,
    attr_firestrategymonitorpercent,
    attr_firestrategypointzoneprcnt,
    attr_fsjobcode,
    attr_fsoverridecode,
    attr_gacc,
    attr_ics209reportdatetime AS ics209_report_datetime,
    attr_ics209rptfortimeperiodfrom AS ics209_report_period_from,
attr_ics209rptfortimeperiodto AS ics209_report_period_to,
    attr_ics209reportstatus,
    attr_incidentmanagementorg,
    attr_incidentname,
    attr_incidentshortdescription,
    attr_incidenttypecategory,
    attr_incidenttypekind,
    attr_initiallatitude,
    attr_initiallongitude,
    attr_initialresponseacres,
    attr_initialresponsedatetime AS initial_response_datetime,
    attr_irwinid,
    attr_isfirecauseinvestigated,
    attr_isfirecoderequested,
    attr_isfsassisted,
    attr_ismultijurisdictional,
    attr_isquarantined,
    attr_isreimbursable,
    attr_istrespass,
    attr_isunifiedcommand,
    attr_isvalid,
    attr_localincidentidentifier,
    attr_modifiedbysystem,
    attr_percentcontained,
    attr_percentperimtobecontained,
    attr_poocity,
    attr_poocounty,
    attr_poodispatchcenterid,
    attr_poofips,
    attr_poojurisdictionalagency,
    attr_poojurisdictionalunit,
    attr_poojurisdictunitparentunit,
    attr_poolandownercategory,
    attr_poolandownerkind,
    attr_poolegaldescprincipalmerid,
    attr_poolegaldescqtr,
    attr_poolegaldescqtrqtr,
    attr_poolegaldescrange,
    attr_poolegaldescsection,
    attr_poolegaldesctownship,
    attr_poopredictiveserviceareaid,
    attr_pooprotectingagency,
    attr_pooprotectingunit,
    attr_poostate,
    attr_predominantfuelgroup,
    attr_predominantfuelmodel,
    attr_primaryfuelmodel,
    attr_secondaryfuelmodel,
    attr_totalincidentpersonnel,
    attr_uniquefireidentifier,
    attr_forid,
    attr_wfdssdecisionstatus,
    attr_estimatedfinalcost,
    attr_organizationalassessment,
    attr_stratdecisionpublishdate AS strat_decision_publish_date,
    attr_createdondatetime_dt AS attr_created_on_datetime,
    attr_modifiedondatetime_dt AS attr_modified_on_datetime,
    attr_source,
    attr_iscpxchild,
    attr_cpxname,
    attr_cpxid,
    attr_sourceglobalid,
    globalid,

    -- Geometry Handling
    wkt_geometry, -- Keep original WKT for debugging/reference if desired
    wkt_geometry AS perimeter_geography -- Convert WKT to GEOGRAPHY

FROM source_seed

WHERE wkt_geometry IS NOT NULL
