-- Optional: Configure as view (default) or table
{{ config(materialized='view') }}

WITH test_participants AS (
    SELECT *
    FROM {{ ref('TEST_PARTICIPANTS') }}
),

final AS (
    SELECT
        -- References use exact UPPERCASE column names from the DDL
        a.INFLUENCE AS INFLUENCE_LEVEL,
        a.PARTICIPANT AS PARTICIPANT_ID,
        a.JOINED_DATE AS SURVEY_JOIN_DATE,
        a.CIVILITY_PLEDGE AS CIVILITY_PLEDGE_STATUS,
        a.TOPIC_THEMES AS DISCUSSION_TOPICS,
        a.WHAT_IS_YOUR_PERSPECTIVE_ON_LA_S_RECOVERY_ AS LA_RECOVERY_PERSPECTIVE,
        a.YOUR_VIEWS AS ADDITIONAL_VIEWS,
        a.IF_YOU_HAD_A_HOME_OR_BUSINESS_DAMAGED_OR_LOST_OR_LOST_EMPLOYMENT_OR_INCOME_TO_THE_RECENT_FIRES_IN_LA_SELECT_THE_ZIP_CODE_OF_THAT_HOME_BUSINESS_OR_PLACE_OF_EMPLOYMENT_ AS FIRE_IMPACTED_ZIP,
        REGEXP_SUBSTR(a.IF_YOU_HAD_A_HOME_OR_BUSINESS_DAMAGED_OR_LOST_OR_LOST_EMPLOYMENT_OR_INCOME_TO_THE_RECENT_FIRES_IN_LA_SELECT_THE_ZIP_CODE_OF_THAT_HOME_BUSINESS_OR_PLACE_OF_EMPLOYMENT_, '\\b\\d{5}\\b') AS FIRE_IMPACTED_ZIP_CLEAN,
        a.WHAT_MUST_BE_ADDRESSED_FIRST_TO_ENSURE_A_SUCCESSFUL_RECOVERY_ AS RECOVERY_PRIORITY,

        -- Apply NULLIF to the exact raw UPPERCASE column names
        NULLIF(a.AMERICAN_INDIAN_OR_ALASKA_NATIVE_WRITE_IN, '') AS AI_AN_WRITEIN,
        NULLIF(a.TERMS_I_AGREE_TO_THE_MODERATION_POLICY, '') AS MODERATION_POLICY_AGREEMENT,
        NULLIF(a.ARE_YOU_A_HOMEOWNER_RENTER_OR_UNHOUSED_, '') AS HOUSING_STATUS,
        NULLIF(a.ARE_YOU_UNEMPLOYED_OR_UNDEREMPLOYED_AS_A_RESULT_OF_THE_LA_FIRES_, '') AS FIRE_IMPACT_EMPLOYMENT,
        NULLIF(a.ASIAN_DETAILED_CATEGORIES, '') AS ASIAN_DETAILED,
        NULLIF(a.WHAT_WAS_YOUR_HOUSEHOLD_INCOME_BEFORE_TAXES_LAST_YEAR_, '') AS HOUSEHOLD_INCOME_PRETAX,
        NULLIF(a.ASIAN_WRITE_IN, '') AS ASIAN_WRITEIN,
        NULLIF(a.BLACK_OR_AFRICAN_AMERICAN_DETAILED_CATEGORIES, '') AS BLACK_DETAILED,
        NULLIF(a.BLACK_OR_AFRICAN_AMERICAN_WRITE_IN, '') AS BLACK_WRITEIN,
        NULLIF(a.HISPANIC_OR_LATINO_DETAILED_CATEGORIES, '') AS HISP_LATINO_DETAILED,
        NULLIF(a.HISPANIC_OR_LATINO_WRITE_IN, '') AS HISP_LATINO_WRITEIN,
        NULLIF(a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_DETAILED_CATEGORIES, '') AS MENA_DETAILED,
        NULLIF(a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_WRITE_IN, '') AS MENA_WRITEIN,
        NULLIF(a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_DETAILED_CATEGORIES, '') AS NHPI_DETAILED,
        NULLIF(a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_WRITE_IN, '') AS NHPI_WRITEIN,
        NULLIF(a.WHITE_DETAILED_CATEGORIES, '') AS WHITE_DETAILED,
        NULLIF(a.WHITE_WRITE_IN, '') AS WHITE_WRITEIN,

        -- CASE statement updated to use exact raw UPPERCASE column names
        CASE
            WHEN
                (CASE WHEN a.AMERICAN_INDIAN_OR_ALASKA_NATIVE_WRITE_IN IS NOT NULL AND a.AMERICAN_INDIAN_OR_ALASKA_NATIVE_WRITE_IN != '' THEN 1 ELSE 0 END) +
                (CASE WHEN (a.ASIAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.ASIAN_WRITE_IN IS NOT NULL AND a.ASIAN_WRITE_IN != '') THEN 1 ELSE 0 END) +
                (CASE WHEN (a.BLACK_OR_AFRICAN_AMERICAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.BLACK_OR_AFRICAN_AMERICAN_WRITE_IN IS NOT NULL AND a.BLACK_OR_AFRICAN_AMERICAN_WRITE_IN != '') THEN 1 ELSE 0 END) +
                (CASE WHEN (a.HISPANIC_OR_LATINO_DETAILED_CATEGORIES IS NOT NULL AND a.HISPANIC_OR_LATINO_DETAILED_CATEGORIES != '') OR (a.HISPANIC_OR_LATINO_WRITE_IN IS NOT NULL AND a.HISPANIC_OR_LATINO_WRITE_IN != '') THEN 1 ELSE 0 END) +
                (CASE WHEN (a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_WRITE_IN IS NOT NULL AND a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_WRITE_IN != '') THEN 1 ELSE 0 END) +
                (CASE WHEN (a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_DETAILED_CATEGORIES IS NOT NULL ) OR (a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_WRITE_IN IS NOT NULL AND a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_WRITE_IN != '') THEN 1 ELSE 0 END) +
                (CASE WHEN (a.WHITE_DETAILED_CATEGORIES IS NOT NULL ) OR (a.WHITE_WRITE_IN IS NOT NULL AND a.WHITE_WRITE_IN != '') THEN 1 ELSE 0 END) > 1
            THEN 'Multi-Race'

            WHEN a.AMERICAN_INDIAN_OR_ALASKA_NATIVE_WRITE_IN IS NOT NULL AND a.AMERICAN_INDIAN_OR_ALASKA_NATIVE_WRITE_IN != '' THEN 'American Indian or Alaska Native'
            WHEN (a.ASIAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.ASIAN_WRITE_IN IS NOT NULL AND a.ASIAN_WRITE_IN != '') THEN 'Asian'
            WHEN (a.BLACK_OR_AFRICAN_AMERICAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.BLACK_OR_AFRICAN_AMERICAN_WRITE_IN IS NOT NULL AND a.BLACK_OR_AFRICAN_AMERICAN_WRITE_IN != '') THEN 'Black or African American'
            WHEN (a.HISPANIC_OR_LATINO_DETAILED_CATEGORIES IS NOT NULL AND a.HISPANIC_OR_LATINO_DETAILED_CATEGORIES != '') OR (a.HISPANIC_OR_LATINO_WRITE_IN IS NOT NULL AND a.HISPANIC_OR_LATINO_WRITE_IN != '') THEN 'Hispanic or Latino'
            WHEN (a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_DETAILED_CATEGORIES IS NOT NULL ) OR (a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_WRITE_IN IS NOT NULL AND a.MIDDLE_EASTERN_OR_NORTH_AFRICAN_WRITE_IN != '') THEN 'Middle Eastern or North African'
            WHEN (a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_DETAILED_CATEGORIES IS NOT NULL ) OR (a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_WRITE_IN IS NOT NULL AND a.NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER_WRITE_IN != '') THEN 'Native Hawaiian or Pacific Islander'
            WHEN (a.WHITE_DETAILED_CATEGORIES IS NOT NULL ) OR (a.WHITE_WRITE_IN IS NOT NULL AND a.WHITE_WRITE_IN != '') THEN 'White'

            ELSE NULL
        END AS RACE_ETHNICITY

    FROM {{ source('ETHELO', 'SURVEY_BY_EMAIL') }} AS a
    LEFT JOIN test_participants AS b ON a.PARTICIPANT = b.participant_id
    WHERE b.participant_id IS NULL AND LENGTH(a.PARTICIPANT) = 36
)

SELECT * FROM final