name: cleanup-tests
on:
  pull_request:
    types:
      - closed

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_RAW_DB: RAW_ENGCA_PRD
  DBT_ANALYTICS_DB: ANALYTICS_ENGCA_DEV
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_ROLE: TRANSFORMER_ENGCA_DEV
  SNOWFLAKE_WAREHOUSE: TRANSFORMING_XS_ENGCA_DEV
  SNOWFLAKE_DATABASE: TRANSFORM_ENGCA_DEV
  SNOWFLAKE_SCHEMA: GH_CI_PR_${{ github.event.number }}
  LLM_MODEL_LOW: ${{ secrets.LLM_MODEL_LOW}}
  LLM_MODEL_MED: ${{ secrets.LLM_MODEL_MED}}
  LLM_MODEL_HIGH: ${{ secrets.LLM_MODEL_HIGH}}
  LLM_MODEL: ${{ github.ref == 'refs/heads/main' && secrets.LLM_MODEL_HIGH || secrets.LLM_MODEL_LOW }}

jobs:
  cleanup-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Cleanup after tests
        run: |
          uv run dbt run-operation drop_schemas_with_prefix \
          --project-dir transform \
          --args "{\"database_name\": \"$SNOWFLAKE_DATABASE\", \"prefix\": \"$SNOWFLAKE_SCHEMA\"}"
          uv run dbt run-operation drop_schemas_with_prefix \
          --project-dir transform \
          --args "{\"database_name\": \"$DBT_ANALYTICS_DB\", \"prefix\": \"$SNOWFLAKE_SCHEMA\"}"
