name: nightly
on:
  schedule:
    # Run a nightly job in the 5AM hour
    - cron: "21 12 * * *"
    # Run a daily job in the 2pm hour
    - cron: "33 14 * * *"
  # Also allow for manual triggers
  workflow_dispatch:

env:
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_PRD }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_PRD }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Build dbt project
        env:
          DBT_PROFILES_DIR: transform/ci
          DBT_ANALYTICS_DB: ANALYTICS_ENGCA_PRD
          DBT_RAW_DB: RAW_ENGCA_PRD
          SNOWFLAKE_ROLE: TRANSFORMER_ENGCA_PRD
          SNOWFLAKE_DATABASE: TRANSFORM_ENGCA_PRD
          SNOWFLAKE_WAREHOUSE: TRANSFORMING_XS_ENGCA_PRD
        run: |
          uv run dbt deps --project-dir transform --target prd
          uv run dbt build --project-dir transform --target prd
