name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_RAW_DB: RAW_ENGCA_PRD
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_ROLE: READER_ENGCA_DEV
  SNOWFLAKE_WAREHOUSE: REPORTING_XS_ENGCA_DEV
  SNOWFLAKE_DATABASE: TRANSFORM_ENGCA_DEV
  LLM_MODEL_LOW: ${{ secrets.LLM_MODEL_LOW}}
  LLM_MODEL_MED: ${{ secrets.LLM_MODEL_MED}}
  LLM_MODEL_HIGH: ${{ secrets.LLM_MODEL_HIGH}}
  LLM_MODEL: ${{ github.ref == 'refs/heads/main' && secrets.LLM_MODEL_HIGH || secrets.LLM_MODEL_LOW }}
  GO_VOCAL_CLIENT_ID: ${{ secrets.GO_VOCAL_CLIENT_ID }}
  GO_VOCAL_CLIENT_SECRET: ${{ secrets.GO_VOCAL_CLIENT_SECRET }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dbt deps
        run: uv run dbt deps --project-dir transform
      - uses: pre-commit/action@v3.0.1
