name: tests
on: pull_request

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_RAW_DB: RAW_ENGCA_PRD
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_ROLE: TRANSFORMER_ENGCA_DEV
  SNOWFLAKE_WAREHOUSE: TRANSFORMING_XS_ENGCA_DEV
  SNOWFLAKE_DATABASE: TRANSFORM_ENGCA_DEV
  SNOWFLAKE_SCHEMA: GH_CI_PR_${{ github.event.number }}

jobs:
  build-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-path: .venv
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Build dbt project
        run: |
          poetry run dbt deps --project-dir transform
          poetry run dbt build --project-dir transform
